### ISSUE TITLE
Suddenly, argparse(what was that!?) usage on assigment.

### ISSUE THREAD

**Issue by ZhaoYun17** [realpython/support#138]
It was so good all along, well written tutorial with great humor.

Then I reach assignment "how to split an CSV file" and totally thrown off by the argparse usage. It feels like a sudden spike in the learning curve since I (and I am sure most of the beginners) start with absolute no idea what that was and how to use that. Some teaching on that topic prior to the assignment would be much appreciated. 

Now I will just try to understand the documentation or maybe look around youtube for some explanation. Sigh.

**Comment by michael2112** [comment]
I liked the challenge! The thought I had when I realized argparse had not been discussed was that it was done in the spirit of the courses -- That this covers ^"Real" world applications and in the real world not everything is found in one source and there is a lot of trial and error in solving problems.  This forces the reader to get out and learn to use other sources for reference, as well as break down the problem into smaller pieces.  My code started out as simply echoing the arguments from the command line before I even moved on to the csv file portion...

**Comment by mjhea0** [comment]
Thanks for the feedback @michael2112. I agree with your assessment, so I am going to leave the courses as they are. Thanks again!
