### ISSUE TITLE
Book 1 8.7 Monte Carlo Exercise

### ISSUE THREAD

**Issue by ChillTrain** [realpython/support#150]
Just a little something I noticed:

If we run the code as written in the book:

    for trial in range(0, 10000):
        while randint(0, 1) == 0:
            tails = tails + 1
        heads = heads + 1

Problem is we are only incrementing in the range when the test is heads, so every time the test is tails it's essentially adding another test to the trial.  Makes more sense to me to replace everything in the for loop with an if/else, then program only runs the determined number of trials specified in the for loop.

I'm really enjoying the content so far.  Thanks!

**Comment by mjhea0** [comment]
So, something like this-

```
for trial in range(0, 10000):
    test = randint(0, 1)
    if test == 0:
        tails += 1
    else:
        heads += 1
for trial in range(0, 10000):
    test = randint(0, 1)
    if test == 0:
        tails += 1
    else:
        heads += 1for trial in range(0, 10000):
    test = randint(0, 1)
    if test == 0:
        tails += 1
    else:
        heads += 1
```

**Comment by michael2112** [comment]
I think the way it is originally is correct. The problem statement before the code describes a "trial" as possibly including multiple flips.  The only trial with one flip of the coin is when heads comes up first...
