### ISSUE TITLE
Book 2 Chapter 7 Decorators

### ISSUE THREAD

**Issue by textheadmin** [realpython/support#153]
I started with book one and as far a I remember the login_required function is the first time the reader has really been required to understand how Python decorators work, not the most simple of topics for the noobish Pythonista.  I spend a good couple of hours on this before feeling pretty confident that I knew what was going on in login_required function and @login_required decorator.

All that to say I found this blog post highly helpful for learning the ins and outs of Python decorators, I think it would be a great reference to add to the book.

http://simeonfranklin.com/blog/2012/jul/1/python-decorators-in-12-steps/

**Comment by mjhea0** [comment]
Have you seen this blog post? https://realpython.com/blog/python/primer-on-python-decorators/

What do you think?

Anyway, I'll add both resources to the course. Thanks!

**Comment by textheadmin** [comment]
Yeah, I like that one even better.  Thanks!
