### ISSUE TITLE
SQL section: Please mention that you need a "," in some case

### ISSUE THREAD

**Issue by ZhaoYun17** [realpython/support#154]
What I means is:
c.execute("SELECT * FROM wateva WHERE model=?",(r[1],))
--------------------------------------------------------------------------^^THIS LAST COMMA!

Just spent half an hour tracking why sql took my input as number of letters instead of a string, only to find out that it is all because of that little devil!

I think adding a note pointing this out in the SQL section can save a lot of hairs from being pulled out =)

(PS: am having a blast learning from the book, good job!! =D)

**Comment by mjhea0** [comment]
Updated.
