### ISSUE TITLE
Serving Static Files in Development

### ISSUE THREAD

**Issue by maxnathaniel** [realpython/support#156]
Hi,

I have been following Real Python Book 2. For Django Blog App, I am unable to serve static files (CSS, JS) files.

I've been searching for answers all over the web, but there are too many conflicting solutions. Can someone help with it?

Thank you.

**Comment by mjhea0** [comment]
Are you using Heroku?

**Comment by maxnathaniel** [comment]
Hey Michael,

I am still on the development stage. Still learning how to build a proper django app. But I found the answer to it on stackoverflow. 

Thanks!

**Comment by mjhea0** [comment]
Awesome!
