### ISSUE TITLE
The line """pb.set_trace()""" missing in your example code

### ISSUE THREAD

**Issue by ZhaoYun17** [realpython/support#158]
Book 2-> chapter 8 Interlude: Debugging in Python -> 8.1 workflow -> step 3

SUPPOSE TO BE:
while True:
    print "To exit this game type 'exit'"
    pdb.set_trace()
    answer = raw_input("What is {} times {}? ".format(
        choice(random2), choice(random1)) )

In the example you shown, the line """"pdb.set_trace()""" wasn't there

YOURS:
while True:
    print "To exit this game type 'exit'"
    answer = raw_input("What is {} times {}? ".format(
        choice(random2), choice(random1)) )

**Comment by mjhea0** [comment]
Updated. This will be in the next release. Thanks!
