### ISSUE TITLE
Book Two Unit Tests .data is Being Deprecated

### ISSUE THREAD

**Issue by ChillTrain** [realpython/support#159]
According to the Werkzeug documentation here:

http://werkzeug.pocoo.org/docs/0.9/wrappers/#werkzeug.wrappers.BaseResponse.data

Since it's going to be deprecated, the call to `response.data` should probably be replaced with a call to `response.get_data()`.  Might as well learn it right the first time.

**Comment by mjhea0** [comment]
Thanks!
