### ISSUE TITLE
Book 2 Unit Tests Pg 197 No login() Function

### ISSUE THREAD

**Issue by ChillTrain** [realpython/support#160]
On page 197 it says:
> Start by adding two more helper methods:

But only the `logout()` function is shown.  I'm assuming since the next test calls it, the second helper function should be `login()` which looks something like this:

```
def login(self, name, password):
        return self.app.post('/', data=dict(name=name, password=password),
        follow_redirects=True)
```

**Comment by mjhea0** [comment]
This is now updated. Thanks!

```python
def login(self, name, password):
    return self.app.post('/', data=dict(
        name=name, password=password), follow_redirects=True)
```
