### ISSUE TITLE
Possible Code Error Part 2, Chapter 6

### ISSUE THREAD

**Issue by mikeyprog** [realpython/support#165]
Part2, chapter 6, Inserting Data.  

On pg. 64 of the part2.pdf, this code throws an error:

```python
cursor.execute("INSERT INTO population VALUES('New York City', 
     'NY', 8200000)")
cursor.execute("INSERT INTO population VALUES('San Francisco', 
     'CA', 800000)")
```
Error:
 File "sqlb.py", line 14
    cursor.execute("INSERT INTO population VALUES('New York City', 
                                                                  ^
SyntaxError: EOL while scanning string literal

Im new to python, so Im not sure if this is an error in the book or with me, but I was able to keep the double line formatting with \ at the end of the first line.

```python
cursor.execute("INSERT INTO population VALUES('New York City', \
     'NY', 8200000)")
```

**Comment by mjhea0** [comment]
updated. thanks!
