### ISSUE TITLE
VirtualEnv deprecated option used in book 2

### ISSUE THREAD

**Issue by avcreation** [realpython/support#167]
Hi,

In part 3.5 of book 2, you are using `virtualenv --no-site-packages`. This option is deprecated since it's the default behaviour.

Don't know if it's better to explicitly write it down for new virtualenv users, but it can be confusing if they are looking for the Official documentation.

Cheers,

**Comment by mjhea0** [comment]
I changed to just -

```sh
$ virtualenv env
```

Thanks!
