### ISSUE TITLE
unclear wording in realpython training book

### ISSUE THREAD

**Issue by BaconEnvelope** [realpython/support#169]
in part 2 of the realpython book, under the "BDD" chapter
on page 334 under "Environmental control", step 1 the wording is as follows:

"1.Create an environment.py file within your “features”file"

is this supposed to say "within your "features folder"??
if I make environment.py in the features folder it doesn't work

I'm not sure what it means to put a .py file in another file. 

Sorry if I am misunderstanding, but this part has me stuck.

**Comment by mjhea0** [comment]
Apologies. It should read:

> Create an *environment.py* file within your "features" folder
