### ISSUE TITLE
broken URL in book2

### ISSUE THREAD

**Issue by BaconEnvelope** [realpython/support#170]
Under the [Homework] section of book 2, the URL for [this] in the following text is broken:

Read [this] article providing a high-level overview of standards associated with RESTful APIs

broken URL:
http://devo.ps/blog/2013/03/22/designing-a-restful-api-that-doesn-t-suck.html

**Comment by mjhea0** [comment]
http://devo.ps/blog/designing-a-restful-api-that-doesn-t-suck/

updated - thanks!
