### ISSUE TITLE
Book2: Interlude:Introduciton to Javascript and jQuery. It's weird.

### ISSUE THREAD

**Issue by ZhaoYun17** [realpython/support#171]
Feel free to ignore this if you find that there is something I obviously missed and not the problem for the tutorial, cause now I have so many questions I felt that I missed something.

1) main.js file, you instruct to create but has no mention where should it be saved.
2) index.html, you instruct to open but there is no "index.html" created in previous project. ?

I am beginning to think that I am not looking at the same exercise as the tutorial is at.

**Comment by mjhea0** [comment]
You probably missed part 1 - **Interlude: Introduction to HTML and CSS**. That sets up the basic HTML and CSS along with the project structure.
