### ISSUE TITLE
problem with flask-bcrypt install

### ISSUE THREAD

**Issue by BaconEnvelope** [realpython/support#173]
There is an issue in Betav6 RealPython part 2 
in the pdf version it's on p276

under "Setup Flask-Bcrypt" section header
these instructions will fail:

pip install flask-bcrypt

this will fail because you need to have python-dev installed

TO REPRODUCE:
checkout code for flasktaskr-05 and build your virtualenv using the requirements.txt

[[when you try to install flask-bcrypt you will get a 'fatal error']]

TO FIX:
sudo apt-get install python-dev
pip install flask-bcrypt

**Comment by mjhea0** [comment]
Thanks!
