### ISSUE TITLE
Real Python Part 2 - Page 96

### ISSUE THREAD

**Issue by Markus-** [realpython/support#174]
The hint with creating the SECRET_KEY by applying the os.urandom-function is kind of heavy to follow.

The output is a byte-literal (python3) and some hard-to-read-stuff in python2.
Probably you adjust the example to a ready-to-use-one?

Regards
Markus

**Comment by mjhea0** [comment]
updated:

> **WARNING**: Make the value of your secret key really, really hard, if not impossible, to guess. Use a random key generator to do this. Never, ever use a value you pick on your own. Or you can use your OS to get a random string:
>
>       >>> import os
>       >>> os.urandom(24)
>       'rM\xb1\xdc\x12o\xd6i\xff+9$T\x8e\xec\x00\x13\x82.*\x16TG\xbd'
>
> Now you can simply assign that string to the secret key: `SECRET_KEY = rM\xb1\xdc\x12o\xd6i\xff+9$T\x8e\xec\x00\x13\x82.*\x16TG\xbd`
