### ISSUE TITLE
Chapter 8 Refactoring (Page 117) incomplete

### ISSUE THREAD

**Issue by Markus-** [realpython/support#178]
After refactoring the result is still "Wrong!".

Problem is, you compare a string (answer = raw_input...) with an int (num1*num2). 
The answer must be converted (int(answer)).

Regards
Markus

**Comment by mjhea0** [comment]
Hi Markus - Which course is this from? 1, 2 or 3? Thanks!

**Comment by Markus-** [comment]
Hi Michael,

sorry - its the second on (Debugging with pdb)

Regards
Markus



Am 28.02.2015 um 12:43 schrieb Michael Herman <notifications@github.com<mailto:notifications@github.com>>:


Hi Markus - Which course is this from? 1, 2 or 3? Thanks!

**Comment by mjhea0** [comment]
This has been updated. It will be in the new release, which should released on Friday - March 27th.
