### ISSUE TITLE
Real Python part1 - Typo

### ISSUE THREAD

**Issue by aseelsky** [realpython/support#179]
I think I found some typing error in the book:

Real Python Part 1
    Page 49
        1. In Python, xy is calculated by using the expression x ** y
        1. In Python, x^y is calculated by using the expression x ** y
    
    page 167
        2nd paragraph: su () it chould be: sub()
        3rd paragraph: ? is upside down

**Comment by michael2112** [comment]
Re: page 49, I think they probably meant to have the first equation's "y" superscripted...

**Comment by mjhea0** [comment]
updated - thanks! :+1:
