### ISSUE TITLE
django ecommerce contact page issue

### ISSUE THREAD

**Issue by kmb346** [realpython/support#180]
Hi guys,

I downloaded your course a few months ago and after working my way through most of the original course I have now completed many of the web development examples as well.  I find them quite interesting and very easy to follow.  Thank you for all your hard work in developing such a great course.

I do have a question about the Django Ecommerce project.  I have gotten to the end and almost everything is working correctly.  However I found that when I click on the contact link the header bar options change from Login to Logout and the Register option disappears.  It seems to assume that I have logged in when in fact I haven’t.  This also leads to more problems since if you click on the logout button you get an error since there is no user found.  I tried substituting your code in place of mine and found the same thing happening.  I was just wondering if there is a way to correct this or if it is possibly covered in the third course (which I will be starting soon).  I appreciate any suggestions.  Thanks and I look forward to completing more of this course.  

Regards,

Kevin Behrens

**Comment by mjhea0** [comment]
Hi Kevin - I assume that this is from the end of course 2. This error is intended and it is fixed in the 3rd course. Please email me at michael at realpython dot com for further explantation. Thanks!
