### ISSUE TITLE
Add English subtitles for all videos

### ISSUE THREAD

**Issue by luzfcb** [realpython/support#181]
Add English subtitles for all videos (or make the life of non-English speakers less complicated).
Hello, my current ability to understand spoken English is very limited.
I have several friends who also take a long time to get to learn English enough to understand spoken English.

I believe available, in a first moment, add subtitles in English for the videos would be of great help to the huge population (~4x the number of native English speakers([calculated based on data from wikipedia](http://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers))) that does not have English as their native language and primary.

In a second moment, add subtitles in other languages.
I've worked with video editing and subtitling and I know how this can be time consuming. However, everything has to start somewhere.

Recently discovered http://www.amara.org/ platform. It is designed to do exactly that, a simplified way to  make Captions, subtitles, and translations for videos.

I particularly would love to have subtitles in my native language Brazilian Portuguese.
The Brazilian community tends to create very fast translations, provided there is at least the version in English.

@j1z0 @mjhea0 @fheisler What is your opinion about this? That would be viable?

**Comment by mjhea0** [comment]
We're discussing this. It won't be for a while if it does get implemented. I am going to go ahead and close this for now. Best!
