### ISSUE TITLE
Web Dev 2 - missing Flask repos - coverage & nosetest issues

### ISSUE THREAD

**Issue by mperham2** [realpython/support#188]
Hi Michael,

I'm enjoying going through the course, albeit slowly. Two problems I've run into both 2 months ago and as I've been repeating some sections now. 

Where are the step-wise Flask repos? Like flasktaskr-03 (01, 02, etc.)? I thought they were in this realpython github account, but can't find them anywhere. 

Also, in 13.2 and 13.3, it's like your tag syntax has jumped ahead to the later parts with blueprints and there is a more complicated file structure (e.g. --omit=../env/* should just be --omit=env/* in 13.2 and in 13.3 this: “nosetests --with-coverage --cover-erase --cover-package=../project”, should be this: "“nosetests --with-coverage --cover-erase --cover-package=.” - there is no "project" at this stage, which was "app" in v3.) I think what I'm saying is correct. 

Enjoying the course and I just wish I could go faster to keep up with new stuff you put in the blog too. 

-Mike

**Comment by mjhea0** [comment]
Hi Mike -

1. You can find the exercises at https://github.com/realpython/book2-exercises
1. Which version of the courses are you on? I updated it last week. We're on Beta v7. If you need the updated version, please email info at realpython dot com. This should clear up the confusion.

**Comment by mperham2** [comment]
Thanks for your help. 
I switched from v3 to v7 in the middle, which may be some of the confusion. I seem to have missed the part where we start putting files in the "project" subdirectory of the "flasktaskr" directory.
