### ISSUE TITLE
With rest_framework 3+ the create method is brok.e.

### ISSUE THREAD

**Issue by IMAMBAKS** [realpython/support#190]
![image](https://cloud.githubusercontent.com/assets/5062713/7027453/cefe8738-dd4f-11e4-82ea-e325e98b3bb1.png)
![image](https://cloud.githubusercontent.com/assets/5062713/7027478/f20af4dc-dd4f-11e4-90bc-d2db0fcb5f9e.png)
![image](https://cloud.githubusercontent.com/assets/5062713/7027501/1fa2363a-dd50-11e4-8637-2aa4596a47ee.png)
![image](https://cloud.githubusercontent.com/assets/5062713/7027509/305d4b5e-dd50-11e4-879f-2713656e8861.png)

**Comment by j1z0** [comment]
This course was written before DRF 3 was released, and thus is not intended for use with DRF 3.  For the time bing please stick with DRF 2.4.3 as stated in the course, as DRF 3 has significant changes.  We will update the chapter to use DRF 3 in the coming months.

**Comment by mjhea0** [comment]
@IMAMBAKS The course has been updated to DRF 3. The new release should be out on Friday.
