### ISSUE TITLE
zev

### ISSUE THREAD

**Issue by mjhea0** [realpython/support#195]
all of zev's issues :)

**Comment by zevav** [comment]
oh man, i've got a lot of issues.  :)

**Comment by zevav** [comment]
9.8 tasks() doesn't have a cursor object or .commit()

**Comment by zevav** [comment]
neither does 9.9 new_task()

**Comment by zevav** [comment]
9.5 i think you want a "error = None" at the top of login()

**Comment by zevav** [comment]
7.10 template needs to get_flashed_messages()

**Comment by zevav** [comment]
7.10 line 11 of blog.py should end with "[title, post])" not "request.form..."

**Comment by zevav** [comment]
7.11 "latter chapter" ---> "later"

**Comment by zevav** [comment]
bk.2 7.8 "Note: Notice how we had to specify a POST..."  This doesn't seem to refer to the context in this location.

**Comment by mjhea0** [comment]
@zevav - which version of the course are you using?

**Comment by zevav** [comment]
goddamnit, "login" is not a verb! ch.7 book 2 :-|  neither is "logout"

**Comment by zevav** [comment]
oh dang, i'm not sure.  using the .mobi version and it doesn't say anywhere that rev it is.  thought it was the latest.

**Comment by zevav** [comment]
just opened beta v7 .mobi in Kindle app, will delete issues that aren't relevant to it.

**Comment by mjhea0** [comment]
@zevav - yes there's a number of changes between 6 and 7 for all of the flasktaskr chapters. it's now python 3 compatible.

**Comment by zevav** [comment]
oh, i see.  so it's valid not to initiate "error = None" in Python 3?  I have no familiarity with 3.

**Comment by mjhea0** [comment]
@zevav - no, `error = None` is valid. I refactored much of the code, which is why `error = None` is gone in certain places.

If you're using Python 2, stick with it. It's compatible with 2 and 3. 

Which chapter did you leave off on in v6?

**Comment by zevav** [comment]
i don't know!  the code i pointed out didn't run without error = None FYI

Zev Averbach
Averbach Transcription
(212) 729-4850
www.avtranscription.com

**Comment by mjhea0** [comment]
You may want to start the flasktaskr chapters over if you don't remember the chapter you left off on

**Comment by zevav** [comment]
oh i definitely didn't start flasktaskr 'til today

Zev Averbach
Averbach Transcription
(212) 729-4850
www.avtranscription.com
