### ISSUE TITLE
I havent received any link after making the payment

### ISSUE THREAD

**Issue by demver** [realpython/support#197]
Hey,

I just made a payment of $60 through my paypal. The payment went through and i wa taken to the page saying "You're all set. We've emailed you a download link and receipt for your records"

I haven't received anything. I checked my spam too.

Please look into this!

Best,
Animesh

**Comment by demver** [comment]
My email Id is : animeshkumar.tile@gmail.com

**Comment by mjhea0** [comment]
contacted via email

**Comment by demver** [comment]
Thanks a lot! The study material is really insightful and covers almost everything i was looking for. Thanks for what you do, again!
