### ISSUE TITLE
FlaskTaskR - Real Python 2 pg 161

### ISSUE THREAD

**Issue by memilanuk** [realpython/support#203]
Book examples set up form validation, but then fails silently - no flash of any errors.  Should be an `else:` statement between the `return redirect(url_for('login'))` and `return render_template('register.html`, form=form, error=error)` to display any errors returned.

@app.route('/register/', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(form.name.data, form.email.data,
                            form.password.data)
            db.session.add(new_user)
            db.session.commit()
            flash('Thanks for registering.  Please login.')
            return redirect(url_for('login'))
    return render_template('register.html', form=form, error=error)

**Comment by mjhea0** [comment]
it will catch it in the return.

**Comment by memilanuk** [comment]
No, it did not.  It failed absolutely silently.

See www.reddit.com/r/flask/comments/32v6lo/af_question_on_wtforms_validators/

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
