### ISSUE TITLE
About git commit

### ISSUE THREAD

**Issue by ni8mr** [realpython/support#207]
Hello, i am reading Real Python tutorials second part. There i have seen these commands-

![capture](https://cloud.githubusercontent.com/assets/6823100/7349720/ea9bce1a-ed1c-11e4-8599-d6bdb2d2b7bb.JPG)

  I am a bit of confused here. Thus these commands mean that we are committing a change in an existing repository? Plus, i have ran these commands in "Git Bash" and it shows error.

**Comment by mjhea0** [comment]
Yes, this updates an existing repo. What's the error?

**Comment by ni8mr** [comment]
Sorry for late reply. I am not much familiar with git. Can you please explain to me why i am seeing this?

![untitle](https://cloud.githubusercontent.com/assets/6823100/7392792/e9af3f74-eeab-11e4-97ea-96c1cefdbee9.png)

**Comment by mjhea0** [comment]
where did you put your .git repo? It doesn't look like it's in like a user folder. The repo must go in the project directory. So, if you have a directory called realpython and then in that directory you have all of your project directories - like hello_world - then the .git repos should go in each of those project directories. 

Make sense?

**Comment by ni8mr** [comment]
Thank you, i have almost solved the issue. I have added my project directory to git bash and than i add this remote folder into my local git repository with "git init". After that everything works, except i am getting messages that - i don't have access to 'origin'

![capture](https://cloud.githubusercontent.com/assets/6823100/7405508/3c6deae4-ef15-11e4-8924-31e5b3235f8a.JPG)

**Comment by mjhea0** [comment]
Did you create the remote repo on Github? If so you need to add the remote URL to your local repo.

**Comment by ni8mr** [comment]
Hello i have solved the issue. I am sorry that i didn't read the earlier chapters of the book. I have added the remote repo first and than push the origin and it has worked.

**Comment by ni8mr** [comment]
Hello i have solved the issue. I am sorry that i didn't read the earlier chapters of the book. I have added the remote repo first and than push the origin and it has worked.
