### ISSUE TITLE
Book Two-Django django.conf.urls.patterns() Deprecated

### ISSUE THREAD

**Issue by ChillTrain** [realpython/support#221]
In book two on 509, the book is suggesting using the urls.patterns() function which is being deprecated:

https://docs.djangoproject.com/en/1.8/releases/1.8/#django-conf-urls-patterns

The code should be reformatted as such:
```python
from django.conf.urls import url
from hello_world import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]
```

**Comment by mjhea0** [comment]
Thanks! This will be reflected in the next release! :+1:
