### ISSUE TITLE
Book Two-TEMPLATE_DIRS Deprecated

### ISSUE THREAD

**Issue by ChillTrain** [realpython/support#222]
In book two on page 512 it says to update the TEMPLATE_DIRS tuple in settings.py.  TEMPLATE_DIRS has been deprecated in 1.8 in favor of the DIRS option of the new TEMPLATES setting:

https://docs.djangoproject.com/en/1.8/ref/settings/#template-dirs

**Comment by mjhea0** [comment]
updated!
