### ISSUE TITLE
Real Python Part 2 p. 196 Test Crashes Shell

### ISSUE THREAD

**Issue by jdbrown371** [realpython/support#225]
I've been following the book rather closely.  I do not use sqlite3 as per the book but configured things to work with Postgres.  Adding db.session.remove() fixed the problem.     

 def tearDown(self):
        db.session.remove()
        db.drop_all()

**Comment by mjhea0** [comment]
Thanks for adding this. The session should be removed as you figured out:

```python
def tearDown(self):
    db.session.remove()
    db.drop_all()
```

I updated the course.
