### ISSUE TITLE
About updating views.py in FlaskTaskr 

### ISSUE THREAD

**Issue by ni8mr** [realpython/support#235]
At the page 230 of the part 2 of Book, we have updated the **complete()** in **views.py** from

    def complete(task_id):
        new_id = task_id
        db.session.query(Task).filter_by(task_id = new_id).update({"status":"0"})
        db.session.commit()
        flash('The task is complete. Nice.')
        return redirect(url_for('tasks'))

to -

    def complete(task_id):
        new_id = task_id
        task = db.session.query(Task).filter_by(task_id=new_id)
        if session['user_id'] == task.first().user_id:
            task.update({"status": "0"})
            db.session.commit()
            flash('The task is complete. Nice.')
            return redirect(url_for('tasks'))
        else:
            flash('You can only update tasks that belong to you.')
            return redirect(url_for('tasks'))

I understand that we are checking the **user_id** in the current session. But i don't understand the term-

    task.first().user_id

I have assumed that it is fetching **user_id** from the **task.first()**, what i am confused about, is the **first()** term.  Why are we using this? (Does it means we are querying the first row- to make sure that the user can not complete the task that are no created by them? )

**Comment by mjhea0** [comment]
`first()` just grabs the first record found (or None if none are found): https://pythonhosted.org/Flask-SQLAlchemy/api.html?highlight=first#flask.ext.sqlalchemy.BaseQuery.first

**Comment by ni8mr** [comment]
Thank you very much ! :)
