### ISSUE TITLE
Is there any design problem for that csv assignment?

### ISSUE THREAD

**Issue by filipeteles** [realpython/support#241]
I just finished a csv assignment and although the output is the same, is there anything wrong or any design problem with my code? It's really different from the included solution.

    import os
    import csv

    my_path = r"C:\path\here\"

    scores_dict = {}
    with open(os.path.join(my_path, "scores.csv"), "r") as my_file:
        my_file_reader = csv.reader(my_file)
        for x, y in my_file_reader:
            scores_dict[x] = y

    for k, v in sorted(scores_dict.items()):
        print(k, v)

**Comment by mjhea0** [comment]
I should have time to look at this later today.

I'm adding the solution we have for reference:

```python
# 10.3 high_scores.py
# Read in CSV data containing names and scores; display a high score list

import csv
import os
my_path = "C:/Real Python/Course materials/Chapter 10/Practice files"

high_scores_dict = {}
with open(os.path.join(my_path, "scores.csv"), "rb") as myFile:
    my_file_reader = csv.reader(myFile)
    for name, score in my_file_reader:  # get each name/score pair
        score = int(score)  # convert string score to integer
        if name in high_scores_dict:  # already had an entry for that name
            if score > high_scores_dict[name]:  # new score is higher
                high_scores_dict[name] = score
        else:  # haven't seen this name yet; add it to dictionary
            high_scores_dict[name] = score

for name in sorted(high_scores_dict):
    print name, high_scores_dict[name]
```
