### ISSUE TITLE
Project Help needed

### ISSUE THREAD

**Issue by alienblogger** [realpython/support#243]
Working on a flask project and have 3 python files that work in the following order

1. Consists of decorators for the urls and then renders the template and passes in variables 
2. Acts as a file reader that reads markdown files and returns the content from the file. 
3. The main app that takes in the url functions and passes in the arguments as a page and the parsed markdown as content 

[Project ZIP](https://drive.google.com/file/d/0BzYRDcVrz12_WFZBTW43Y3NsTVE/view?usp=sharing)

**Comment by mjhea0** [comment]
Do you have a GIthub link to the project? It will be much easier for us to look at. Thanks!

**Comment by alienblogger** [comment]
Thanks @mjhea0  I got a workaround. Thanks again.
