### ISSUE TITLE
Mentoring - No Response from Michael Herman

### ISSUE THREAD

**Issue by nubianMONK** [realpython/support#244]
Hi Michael,

I have tried but to no avail per reaching you. I had made a $250 paypal transfer to you at hermanmu@gmail.com . I sent a number of e-mail but as aforementioned nae luck. Can you kindly reach out to me please. My e-mail address is buddhie2@gmail.com Tel: 215.594.3369.

Regards,
Akin

**Comment by mjhea0** [comment]
My bad. Let's handle this over email. Best!
