### ISSUE TITLE
Small error in Introduction to Python

### ISSUE THREAD

**Issue by michaeljpeake** [realpython/support#245]
On page 116 (117 of the PDF), the output of a text file is shown as:

    ['This is my file.\n', 'There are many like it,\n', 'but this one is mine.', 'NON SEQUITUR']

The third string is missing the newline characters, `\n`. It should be:

    ['This is my file.\n', 'There are many like it,\n', 'but this one is mine.\n’, 'NON SEQUITUR']

**Comment by mjhea0** [comment]
Updated - thanks!
