### ISSUE TITLE
Book 2 - DATABASE / DATABASE_PATH mismatch

### ISSUE THREAD

**Issue by michaeljpeake** [realpython/support#246]
In the code examples on pages 89, 92, 101 of Book 2, the following function is defined:

    def connect_db():
        return sqlite3.connect(app.config['DATABASE_PATH'])

However, the database path is actually defined as `DATABASE` earlier in blog.py. Running the code as it is published will results in an error. 

Either `DATABASE_PATH` should be replaced by `DATABASE` in Chapter 7, or vice versa.

**Comment by memilanuk** [comment]
Just ran into the same thing!

**Comment by mjhea0** [comment]
Updated. Thanks!
