### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by NormalMario** [realpython/support#247]
The thing that really sucks with Python is I've often experienced problems with installing packages. I've got Python 2.7 installed on several computers. I'm in chapter 12 of Python part 1 and wanted to "easy_install reportlab" on my new notebook. It didn't work. I changed directory to \Python27\Scripts ans tried again. It didn't work. I tried 'pip install reportlab'. It didn't work. I tried '.\easy_install reportlab'. It didn't work. I tried '.\pip install reportlab'. This time it did work. Why do I need the prefix ".\" which is not documented? Now that I try "easy_install reportlab" again from another directory it suddenly works. This is confusing, guys and costs time ...

**Comment by marloncruz** [comment]
I feel you. But this has nothing to do with Python
pip and easyinstall are usually located at /usr/local/bin
A good tutorial on running programs on different paths can be found [here] (http://www.linux-tutorial.info/modules.php?name=MContent&pageid=17)

But to answer your question, prefixing with ./ means you are invoking the program from current directory. If the program is not present, then it will not run.
To check the contents of the directory you are in - just type 'ls' (that is small 'L') from the command line.

**Comment by NormalMario** [comment]
Thank you very much, Marlon! Helpful insights.
