### ISSUE TITLE
Same script produces an error every second trial

### ISSUE THREAD

**Issue by NormalMario** [realpython/support#248]
chapter 12, part 1:

from reportlab.pdfgen import canvas
c = canvas.Canvas('hello.pdf')
#c.drawString(100,100,'Hello World')
c.drawString(250,500,'Hello World')
c.save()

The first time I run it it produces this error:

Traceback (most recent call last):
  File "C:/Users/Mario/Documents/Python_Lehrmaterial/RealPython/Uebungen/ex27.py", line 6, in <module>
    c.save()
  File "C:\Python27\lib\site-packages\reportlab\pdfgen\canvas.py", line 1215, in save
    self._doc.SaveToFile(self._filename, self)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 218, in SaveToFile
    f = open(filename, "wb")
IOError: [Errno 22] invalid mode ('wb') or filename: u'hello.pdf'

The second time I run it unchanged it obliges. The third time I run it it produces the error again, the fourth time it obliges, etc. Any idea why that happens? I've had the same result with prior pdf writing examples.

Thanks,
  Mario

**Comment by marloncruz** [comment]
Your code runs perfectly everytime on my machine. Make sure you are not opening the pdf somewhere (Acrobat?) that locks the file.

**Comment by NormalMario** [comment]
Thank you very much, Marlon! I tried it again and now it works indeed. I'm pretty sure I didn't have the pdf opened last time I tried it - but it's okay now.
