### ISSUE TITLE
Calling Google API from the python shell,  label:question

### ISSUE THREAD

**Issue by ni8mr** [realpython/support#249]
Hello, at the 396th page of Real Python-part 2 book, it has been said to call the API (written in the book) from the Python shell. I have tried the **requests** module.

    import requests
    ouput = requests.get("http://maps.googleapis.com/maps/api/directions/jsonorigin=Central+
         +Park&destination=Times+Square&sensor=false&mode=walking")

But i am only able to catch the response-

    <Response [200]>

How can i catch the JSON file to extract the actual driving directions?

**Comment by ni8mr** [comment]
Hello again, for this very same reason **Rotten Tomato API** code section is also not working. The problem is in this part-

    url = requests.get("http://api.rottentomatoes.com/api/public/v1.0/" + "lists/movies/in_theaters.json?apikey=%s" % (YOUR_OWN_KEY,))

As we are getting only the response using **requests.get()**, we can't add it to a string. It is raising a **TypeError**.

**Comment by mjhea0** [comment]
@ni8mr The first issue is because the API no longer accepts `http`; you need to use https://maps.googleapis.com/maps/api/directions/ ... instead.

I double checked the code in the second API call and it works fine from my end. You may want to try using .` format()` instead of `%`.
