### ISSUE TITLE
Error with link to see sample chapter 

### ISSUE THREAD

**Issue by drcp** [realpython/support#250]
Hi,
Is your Real Python site still active? This broken link leads me to believe your company is not active anymore. Do you still offer support for Real Python as advertised?
Thanks, 
Curtis Perry

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: i/MGJJDYYI
RequestId: 627D9F824D1C3656
HostId: ocdL/6cPGC0heKMzX6jmL3e/E0BkYIh29tWCBE0ezLaQ13gmkt5DTnG9SeTVAuc0

**Comment by mjhea0** [comment]
Hi! Make sure you are not right-clicking when trying to download the sample course. If you continue to have problems, please email us at info at realpython dot com. Thanks!
