### ISSUE TITLE
Mentoring by Michael Herman

### ISSUE THREAD

**Issue by nubianMONK** [realpython/support#251]
Hi Michael,

I had to resort to reaching out to you via your issues log, since you've stated that all the e-mails i have sent to all the e-mail addresses I have for you, namely michael@realpython.com, michael@mherman.org & hermanmu@gmail.com have all been going to SPAM. I also sent an e-mail from my corporate e-mail account yesterday (akinbode.2.akinkunmi@gsk.com) rather than my gmail account (buddhie2@gmail.com) in hopes that you will eventually get the mail.

Well you did say to reach out to you on the 15th of August, so that we can kickoff the mentoring sessions, so to that, i have been trying to reach you since the 14th of the month, but with no joy.

Can you kindly reach out to me please, my mobile number is 215.594.3369, i also invited you to join HangOut, if you are more comfortable with that. We can equally catch up on Skype, my holder ID is: danubian2.  

Kind Regards,
Akin

**Comment by mjhea0** [comment]
just emailed you.

**Comment by nubianMONK** [comment]
I have equally replied to your e-mail, with all the details you requested.
