### ISSUE TITLE
Part 2: Misnamed database variable error

### ISSUE THREAD

**Issue by powerlanguage** [realpython/support#252]
On Page 89 of Part 2 (Flask Blog) the `DATABASE` variable is also referred to as `DATABASE_PATH`.  This continues throughout the chapter.

```
DATABASE = 'blog.db'
...
def connect_db():
  return sqlite3.connect(app.config['DATABASE_PATH'])
```

While we are working through the chapter, the code runs at at page 89 as we aren't actually accessing anything from the database.  The issue only becomes apparent in the 'Show Posts' section on page 105.  The fact the error was introduced silently so long ago could make the problem tricky for some to solve.

Additionally, the description of the `app.config.from_object()` method isn't very clear and this confusion is then compounded by the fact that the two variable names in the text don't actually match, yet the program runs (at page 89) as we haven't yet got to accessing variables from the DB.

```
#pulls in app config by looking for UPPERCASE variable
app.config.from_object(__name__)
```

The discrepancy in the text made this concept hard for me to grasp.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
