### ISSUE TITLE
Part 1, Page 8, Typo

### ISSUE THREAD

**Issue by jmssmth** [realpython/support#255]
See attached image
![page 8 typo](https://cloud.githubusercontent.com/assets/1591341/9748350/ade16cbe-5649-11e5-8033-43f5539c637f.png)

**Comment by mjhea0** [comment]
Nice catch!!!

Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
