### ISSUE TITLE
Real Python Part 1 Grammar Error

### ISSUE THREAD

**Issue by zotarm** [realpython/support#256]
1.1 Why this course? paragraph 1 reads: “However, most of the resources out generally have two main problems:”

Should read: “However, most of the resources out <strong>there</strong> generally have two main problems:”

**Comment by mjhea0** [comment]
Nice catch!!!

Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
