### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by powerlanguage** [realpython/support#257]
v1.0.1 Part 2 pg 180 

"Let’s add a few more [validators to]" `forms.py`

The only change is adding `Email()` to the email field.

```
  email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
```

The "few" was a little confusing as I am having to compare code hoping I didn't miss anything.  Pretty sure the `Email()` validator is the only addition.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
