### ISSUE TITLE
The Gdata API has been removed

### ISSUE THREAD

**Issue by MichaelJAndy** [realpython/support#261]
Real Python book part 2 - page 318

Visit the example URL given in the book:
http://gdata.youtube.com/feeds/api/users/username/playlists
Note the response `No longer available`

A quick google will show that the old "gdata" API has been removed:
http://stackoverflow.com/questions/30685625/alternative-for-https-gdata-youtube-com-feeds-api-videos-video-idv-2

I'm guessing that also means the "gdata" module written for Python2 the book is using is basically useless now. 

The guides in this section, if they are to be written to explore the google API should probably be using the new packages installed by `pip install --upgrade google-api-python-client`

Moar about the new library here:
- https://developers.google.com/api-client-library/python/start/installation
- https://developers.google.com/api-client-library/python/
- https://developers.google.com/youtube/v3/getting-started

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv

**Comment by MichaelJAndy** [comment]
Thanks mate!
