### ISSUE TITLE
Incomplete documentation concerning flask deployment to Heroku

### ISSUE THREAD

**Issue by MichaelJAndy** [realpython/support#263]
Error in Real Python Part 2 Ch 15.5
## First error:

When deploying to Heroku there's packages in `requirements.txt` that need Python3 to run, so it'll fail as the default interpreter in Heroku is Python 2.7.

After looking up how it should work you need to make a `runtime.txt` file with the string `python-3.4.3` in there in order to get it working with Python 3, commit and push that and it'll install the requirements and start the app.
## Second error:

You've simply got one line to get Postgres working, and that only installs the add on in Heroku. There's nothing in the app code itself that tells the project to use a Postgres database and there's still code in there that's pointing to an SQLite database.

The error to not include anything in the code regarding a Postgres connection is in your current repo also: https://github.com/realpython/book2-exercises/blob/master/flasktaskr_project/config.py

Also along with that you probably need to run a command to set the database up like `heroku run python3 db_create.py`

My preference would be to have it work on SQLite on my local machine, and then have it somehow configured to work with Postgres when pushed to Heroku, see below for a hacky solution to this.

I wrote a quick workaround, there's probably better ways but it works just to show it's probably only a few lines to fix the SQLite/Postgres Heroku issue:

Edit config.py and put a try catch in there to pick up the Heroku database URL environment variable

```
import os


# grab the folder where this script lives
basedir = os.path.abspath(os.path.dirname(__file__))


CSRF_ENABLED = True
SECRET_KEY = 'my_precious'
DEBUG = False

# Try to get database info from environment variable, if it doesn't exist then use sqlite
try:
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
except Exception as e:
    DATABASE = 'flasktaskr.db'
    DATABASE_PATH = os.path.join(basedir, DATABASE)
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + DATABASE_PATH

```

If it fails trying to get the variable, it'll default back to running SQLite - good enough. Only problem is that if the user happens to have an environment variable set up that's already "DATABASE_URL" it'll probably not work.

Then push to heroku, and don't forget to create the database `heroku run python3 db_create.py`

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv

**Comment by MichaelJAndy** [comment]
Excellent, thanks
