### ISSUE TITLE
I don't have permissions to add labels to this repo

### ISSUE THREAD

**Issue by beatbreaker82** [realpython/support#264]
I'm more of a JIRA guy ;) , but I don't seem to have permissions to add labels in your issue tracker, as the instructions say on https://github.com/realpython/support

>    Click here to add a new ticket
>    Add a descriptive title
>    Add in any notes, comments, feedback into the text box
>    Add a label - bug, feature, question, or other
>    You'll automatically be notified as we address the ticket

I'm not sure I have permissions to add a label in Github given the scheme: https://help.github.com/articles/permission-levels-for-an-organization-repository/

**Comment by mjhea0** [comment]
Actually, I think only admin can update the label.

**Comment by beatbreaker82** [comment]
@mjhea0 ... so shouldn't the readme.md file be updated on https://github.com/realpython/support to reflect that?

**Comment by mjhea0** [comment]
updated

**Comment by beatbreaker82** [comment]
Thank you!
