### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by MichaelJAndy** [realpython/support#266]
Book 2 Page 324

Shows something like this:

```
data = requests.get(url)
binary = data.content
output = json.loads(binary)
print(output['status'])
```

Running that will throw `TypeError: the JSON object must be str, not 'bytes'`

Instead the code should be:

```
r = requests.get(url)
output = json.loads(r.text)
print(output['status'])
```

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv

**Comment by MichaelJAndy** [comment]
Thanks for hearing my contribution.
