### ISSUE TITLE
Rotten Tomatoes no longer hand out API Keys

### ISSUE THREAD

**Issue by MichaelJAndy** [realpython/support#268]
Book 2 Page 327 mentions registering for a Rotten Tomatoes API key, this is no longer possible.

See: http://developer.rottentomatoes.com/member/register

> Rotten Tomatoes is no longer issuing API keys at the time of registration. We will review each application to ensure the usage of our data aligns with Brand Guidelines and Terms of Service and will provision keys if approved. There is now a license fee to access the API details of which will be provided upon application approval. The approval process may take up to 60 days. Thank you for your patience.

Similar exercises could be done through
- TheTvDB http://thetvdb.com/wiki/index.php?title=Programmers_API
- Open Movie Database: http://omdbapi.com/

**Comment by mjhea0** [comment]
closing... looking at your other issue now
