### ISSUE TITLE
Problems with Flasktskr Partt 2

### ISSUE THREAD

**Issue by mcmcgonagle** [realpython/support#270]
Hi,

Great book, love it so far!

Here is the issue I'm having. I switched over to SQLAlchemy in FlaskTskr Part 2 however I cannot add new tasks to the DB and Im getting no error messages when I submit the form. I've been scouring my code and comparing it to the book but it looks identical so far. Any ideas? I can send my code if it helps but I'm hoping you can give me a couple of things to check and I can try to work through it on my own a little bit.

**Comment by mcmcgonagle** [comment]
Error in the Date Due (mm/dd/yyyy) field - This field is required.

I added some error messaging and I keep getting this however, I keep including a date.

**Comment by mcmcgonagle** [comment]
My Code:

{% extends "_base.html" %}
{% block content %}

<h1> Welcome to FlaskTaskr</h1>
<a href="/logout">Logout</a>
<div class="add-task">
    <h3>Add a new task</h3>
        <form action="{{ url_for('new_task') }}" method="post">
            {{ form.csrf_token }}
        <td>
            <label>Task Name</label>
            <input name="name" type="text">
            </td>
            <td>
            <label>Due Date (mm/dd/yyyy): </label>
            <input name="due_date" type="datetime" width="120px">
            </td>
            <td>
                <label>Priority</label>
                <select name="priority" width="100px">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                </select>
            </td>
        <td>
            &nbsp;
            &nbsp;
            <input class="button" type="submit" value="Save">
        </td>
        </form>
</div>
<div class="entries">
    <br>
    <br>
    <h2>Open Tasks:</h2>
    <div class="datagrid">
        <table>
            <thead>
                <tr>
                    <th width="300px"><strong>Task Name</strong></th>
                    <th width="100px"><strong>Due Date</strong></th>
                    <th width="50px"><strong>Priority</strong></th>
                    <th><strong>Actions</strong></th>
                </tr>
            </thead>
            {% for task in open_tasks %}
            <tr>
                <td width="300px">{{ task.name }} </td>
                <td width="100px">{{ task.due_date }} </td>
                <td width="50px">{{ task.priority }} </td>
            <td>
                <a href="{{ url_for('delete_entry', task_id = task.task_id) }}">Delete</a>
                <a href="{{ url_for('complete', task_id = task.task_id) }}">Mark as Complete</a>
            </td>
             </tr>
            {% endfor %}
        </table>
    </div>
    <br>
    <br>
</div>
<div class="entries">
    <h2> Closed tasks</h2>
    <div class="datagrid">
        <table>
            <thead>
                <tr>
                    <th width="300px"><strong>Task Name</strong></th>
                    <th width="100px"><strong>Due Date</strong></th>
                    <th width="50px"><strong>Priority</strong></th>
                    <th><strong>Actions</strong></th>
                </tr>
            </thead>
            {% for task in closed_tasks %}
            <tr>
                <td width="300px">{{ task.name }} </td>
                <td width="100px">{{ task.due_date }} </td>
                <td width="50px">{{ task.priority }} </td>
            <td>
                <a href="{{ url_for('delete_entry', task_id = task.task_id) }}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
</div>

{% endblock %}

**Comment by mcmcgonagle** [comment]
Figured it out. Really Simple issue in forms.py

format='%m%d%Y'

needed to be changed to: 

format='%m/%d/%Y'

**Comment by mjhea0** [comment]
@mcmcgonagle great job figuring this out. Is this an issue with the course? Do I need to update something? Thanks!

**Comment by mcmcgonagle** [comment]
Thanks! I'll double check but I think it was a typo on my part.
