### ISSUE TITLE
Part 2, Page 181, def flash_errors(form)

### ISSUE THREAD

**Issue by ghost** [realpython/support#272]
The code (function) you add to display the error messages to the end user "flash_errors(form)" is never called in the code after that.

found this useful to me:
- http://flask.pocoo.org/snippets/12/
- http://stackoverflow.com/questions/13585663/flask-wtfform-flash-does-not-display-errors

**Comment by powerlanguage** [comment]
Thanks, I was wondering about this too.

**Comment by decherd** [comment]
Agreed, as I worked back through the code I was confused by this function. I then realized it was simply created but never called. I called it just to see how it worked on the registration view by adding in an else statement if the form didn't validate.

**Comment by mjhea0** [comment]
Thanks!

**Comment by sunilmamillapall1** [comment]
Can we have it fixed please. I wasted a considerable amount of time on finding where it's getting called.

**Comment by mjhea0** [comment]
@sunilmamillapall1 I just made the changes, which will be reflected in the next release. Sorry you spent so much time on it.

**Comment by sunilmamillapall1** [comment]
Thanks!
