### ISSUE TITLE
Can't figure out this error

### ISSUE THREAD

**Issue by WikiWookie** [realpython/support#275]
(flsk) PS C:\Users\wooku\realpy\flask-hello-world\flsk> python app.py
 File "app.py", line 4
   4 from flask import Flask
           ^
SyntaxError: invalid syntax

I get this error when trying to run the Hello World flask program on page 48 of real python part 2.  The python version being used is 2.7.10 and it doesn't look like a syntax error, as I have copied it straight from the pdf.  Any ideas?

coolwest@gmail.com

**Comment by Nolapete** [comment]
Old issue, but should be resolved.  You have the number 4 in front of that line of code.  Remove the 4 and it will work.  Always type the code.  Never copy and paste.  You'll gain finger memory from doing so and learn to code faster.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
