### ISSUE TITLE
Error at the end or course #2

### ISSUE THREAD

**Issue by peckzl** [realpython/support#277]
Hi there,

I am getting an error when registering a new user on the ecommerce site. The registration is going through fine though because it is appearing on stripe. Anyway, the error is:

DatabaseError at /register
no such table: payments_user

I have followed your tutorial closely and compared my code to that of your repository. I can't seem to find out what is going wrong.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
