### ISSUE TITLE
Small typo, Part 1, Chapter 21

### ISSUE THREAD

**Issue by mlaman** [realpython/support#281]
On page 280, something seems missing in the sentence structure:

"You start with the class keyword to indicate that you are creating a class, then you add the
name of the class (using CamelCase notation, starting with a capital letter), **and finally add
the class that the you are inheriting from in parentheses** (more on this below)."

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
