### ISSUE TITLE
Stripe mock problem

### ISSUE THREAD

**Issue by petervines** [realpython/support#282]
I am working my way through RealPython Book 3 and I am having some issues getting the stripe tests to work where they use mocks. 

I purchased the course recently with reference: 150901-104-88006
email: peter.vines@gmail.com

Many thanks, Peter.

The following two tests fail:
test_registering_new_user_returns_succesfully
test_registering_user_twice_cause_error_msg
I have commented out some of the other tests that fail for similar reasons. 

The tests fail because I get a 'stripe.InvalidRequestError: No such token: ...' error which I am guessing means that the mock is not working correctly. I have reached chapter 6 and have upgraded to Django 1.8.4 and python 3.4.3. I cannot see what I am doing wrong. I have tried copying your code from github with no success. 

I have attached my requirements.txt, the output from a test run and my payments/testviews.py (as testviews.txt) code.
[requirements.txt](https://github.com/realpython/support/files/55495/requirements.txt)
[testViews.txt](https://github.com/realpython/support/files/55497/testViews.txt)
[test-results.txt](https://github.com/realpython/support/files/55498/test-results.txt)

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
