### ISSUE TITLE
RPFTW: web2py ch 22.11 `crud` not defined

### ISSUE THREAD

**Issue by memilanuk** [realpython/support#283]
Trying to update the controller `default.py` with a function for the note(s) page... my code looks (as far as I can tell) the same as [shown here in the repo, line 26](https://github.com/realpython/book2-exercises/blob/master/py2manager/applications/py2manager/controllers/default.py#L26) but I am getting an error ticket when I try to actually access the page:

```
File "/home/memilanuk/web2py/applications/py2manager/controllers/default.py", line 57, in note
  form = crud.create(db.note) if auth.user else "Login to Post to the Project"
NameError: global name 'crud' is not defined
```

Not sure if its a version thing; I'm using web2py 2.12.3 on pythonanywhere.com, vs. 2.8.2 as used in the book.  Web2py is supposed to be pretty good about backwards compatibility, and I thought `crud` was a standard feature...?

**Comment by memilanuk** [comment]
https://stackoverflow.com/questions/28234422/web2py-global-name-crud-is-not-defined/28238033#28238033

https://groups.google.com/forum/?fromgroups#!newtopic/web2py/web2py/jrMy9btb1V0

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
