### ISSUE TITLE
django-admin.py in virtualenv 

### ISSUE THREAD

**Issue by BjoernLaemmerzahl** [realpython/support#284]
I am following your book on Page 503 of the second part.
A virtuenv is initialized and active and I installed Django with pip. Now the book tells me to use django-admin.py startproject Hello_world_project. However, this means that I use the globally installed Python as associated in Windows, rather than the Python.exe in virtualenv. (see also: http://stackoverflow.com/questions/4837632/django-admin-py-and-virtualenv-issue-on-windows)
![capture](https://cloud.githubusercontent.com/assets/4821787/12218772/66bab0ca-b729-11e5-8068-0dfb4f26fe88.PNG)

What confuses me is, that even with using the "Python" before, I can't get it to work.

I hope this is the right place to ask. Can't wait to continue.

**Comment by mjhea0** [comment]
Try using just `django-admin`:

`$ django-admin startproject hello_world_project`
