### ISSUE TITLE
Never got Kickstarter deal

### ISSUE THREAD

**Issue by pixelandbyte** [realpython/support#286]
Hello:

I was Backer #815 of your Kickstarter campaign for Real Python: Advanced Web Development.  I was going through my documents because I wanted to access the course.  Much to my surprise, I do not have the Real Python: Advanced Web Development course!

Since the Kickstarter campaign ended, I have received numerous updates to courses 1 and 2, the last one being on 12/21/2015 (the continued updates are awesome by the way).  I have not received ANY updates to course 3, nor do I see a link to download the Kickstarter campaign product.

How do I access the Advanced Web Development course?

Thanks!
Sameera Roussi

**Comment by mjhea0** [comment]
Can you email info at real python dot com. Thanks!
