### ISSUE TITLE
Part 1, Page 291 Review exercises: 1. Create a Pet() - ambiguity

### ISSUE THREAD

**Issue by ThinkCode** [realpython/support#289]
First things first, great learning resources. I coded in Python procedural in the past and now am resuming Python learning, OOP emphasis this time. Just bought this yesterday. 

Fantastic OOP primer btw. Page 291 Review exercises: 1. Create a Pet() - ambiguity. When you say : 1. 

> Create a Pet() class that holds instances of dogs;this class is completely separate from the Dog() class. In other words, the Dog() class does not inherit from the Pet() class.

Does that mean Pet() is another brand new class like Dog()? Pet() holding instances of Dogs() is confusing. Please advise.

I have the following code which I think is plain wrong! Can you please elaborate on what you meant with this review exercise or a forum or solutions for exercises somewhere perhaps? Thank you!

```
# Parent class
class Dog(object):
    # Class attribute
    species = 'mammal'
    # Initializer / Instance attributes

    def __init__(self, name, age):
        self.name = name
        self.age = age
    # instance method

    def description(self):
        return "{} is {} years old".format(self.name, self.age)
    # instance method

    def speak(self, sound):
        return "{} says {}".format(self.name, sound)
    # child class (inherits from Dog() class)


class RussellTerrier(Dog):

    def run(self, speed):
        return "{} runs {}".format(self.name, speed)
# child class (inherits from Dog() class)


class Bulldog(Dog):

    def run(self, speed):
        return "{} runs {}".format(self.name, speed)


class Pet(object):
    species = 'mammal'

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def description(self, mypets):
        return "I have {} dogs. {} is {}. {} is {}. {} is {}. And they are all {} of course!".format(mypets.count(),
        mypets[0].name, mypets[0].age, mypets[1].name, mypets[1].age, mypets[2].name, mypets[2], mypets[0].name.species)

Tom = Pet('Tom', 6)
Mike = Pet('Mike', 7)
Larry = Pet('Larry', 9)

mypets = [Tom, Mike, Larry]
```

**Comment by mjhea0** [comment]
I'll look into this in the next few days! Cheers!
