### ISSUE TITLE
Loops chapter missing?

### ISSUE THREAD

**Issue by isabelggc** [realpython/support#291]
Hi there,

I purchased yesterday the whole Real Python course (enjoying it so far), but I observed that in the "Functions and Loops" chapter there is the explanation about the functions, but nothing whatsoever about loops. So I'm wondering... maybe it was removed for some reason? Are loops explained elsewhere?

Cheers,
Zupe

**Comment by mjhea0** [comment]
Hi! My bad. This section was removed erroneously. I just updated the course. Go ahead and re-download. Cheers!
