### ISSUE TITLE
Not received an E-Mail with a download link after (re-)purchasing all three courses

### ISSUE THREAD

**Issue by BrianF84** [realpython/support#292]
Hello,

I'm an early baker of this project and have recently (re-)bought all three courses with a coupon code for 20$ (see my paypal transaction from 25.02.2016, E-Mail "m.wxxxx@freenet.de"). But, unfortunately, I haven't received any E-Mail after this purchase. I have checked all my E-Mail folders, including spam and virus.

Please check my purchase and send me a working download link.

With kind Regards,
Manuel

(I have just seen that this is an public support forum, so I have changed my E-Mail address!)

**Comment by mjhea0** [comment]
Hi. I just sent a download link to the original email address that you supplied. Also, in the future, please email us at info at realpython dot com. Best!
