### ISSUE TITLE
Adapting to new Django file structure

### ISSUE THREAD

**Issue by ni8mr** [realpython/support#294]
It seems from Django 1.9.x, there is a new file structure is introduced. Will Real Python adjust their curriculum to adapt with the new file structure ?

**Comment by j1z0** [comment]
not sure what you mean by "new file structure" do you have a link to some documents that describe that?

**Comment by ni8mr** [comment]
@j1z0    Question has raised in my mind while i was browsing this link - http://stackoverflow.com/questions/32795227/what-is-the-purpose-of-apps-py-in-django-1-9

**Comment by j1z0** [comment]
this is more about how to configure reusable apps, and not so much a "new file structure".  Anyways I am currently in the process of updating the course for 1.9 I'll keep this on in mind and see if it makes sense to work it in.

Thanks for the tip.
