### ISSUE TITLE
Looking for part 1 chapter 6 solutions

### ISSUE THREAD

**Issue by jeffkitterman** [realpython/support#296]
I cannot find them. Can someone please point me in the right direction?
Thanks,
Jeff

**Comment by mjhea0** [comment]
The Interlude Debugging chapter does not have any exercises.

**Comment by jeffkitterman** [comment]
I am referring to 6.6.1 review exercises. Are there solutions for these exercises?

**Comment by mjhea0** [comment]
What's the name of the chapter that you're referring to?

**Comment by jeffkitterman** [comment]
Fundamentals: Functions and Loops

**Comment by mjhea0** [comment]
That's chapter 5 -> https://github.com/realpython/book1-exercises/tree/master/chp05

**Comment by jeffkitterman** [comment]
Thank you. I am apologize for not having looked more closely.
