### ISSUE TITLE
Using Github

### ISSUE THREAD

**Issue by Rchieve** [realpython/support#297]
Hej Real-Python-Team,

I purchased the Real-Python courses just a couple of days ago and till now I am really keen on it! It seems like it is a really good start into the world of programming with python.

I have a little question to setting up git and github. 
1. Why do we set up a local rep for the 'Real-python'-Folder when it is recommended to set up repositories for each project itself? 
2. When it comes to github: Do I create a new repository for each project (e.g. a separate rep for 'Hello-World') or do I use one repository (e.g. Real-python) to store all my projects in it?

I can find information about using github and git for a single project but till now I couldn't find an example with more than one project in a github repository.

Thank you already in advance!

Best regards
Sascha

**Comment by mjhea0** [comment]
Hi Sascha,

You are absolutely correct - Set up individual repositories for each project. We recommend creating a a real-python folder and then adding each project to that folder. Each project, in turn, is a separate .git repo:

```sh
├── real-python
    ├── project1
    └── project2
```
