### ISSUE TITLE
Bug: LearnPython1 pg. 220

### ISSUE THREAD

**Issue by whieronymus** [realpython/support#298]
Hey guys, love the book so far. Just thought I'd point out a couple issues I needed to fix on this page in order to get the code to run. I'm running 3.5.1 if that makes a difference.
1. rom pyPDF2 import PdfFileReader, PdfFileWriter # "P" in PyPDF2 needs to be capitalized
2. rotate_choices = (90, 180, 270) # Only worked for me when I turned the ints into strings

Also I'm having trouble getting NumPy/SciPy installed on Windows. Not sure if y'all can help with that or not. Thanks again for this great course! Enjoying every minute of it!
--Will

**Comment by mjhea0** [comment]
@fheisler ^^
