### ISSUE TITLE
jinja2.exceptions.UndefinedError: form is undefined

### ISSUE THREAD

**Issue by matinde** [realpython/support#302]
Hello, I am at Chapter 11: FlaskTaskr part 3: Error Handling and Unit Testing,  "11.2.7.6 Users can logout"

After inputting the test and changing the logout view, I get the above error: jinja2.exceptions.UndefinedError: form is undefined

I have looked at all the views with those that need the form and I am not sure where I am going wrong here. I have even compared the views.py in the repository with mine and I can't seem to capture where the error is coming from.  

I dont know how to save the page so that you can see the error well. Please let me know if you can help.

**Comment by mjhea0** [comment]
Can you please email michael at reapython dot com. Thank you!
