### ISSUE TITLE
Can't get postgres to work with python 3.5.2 and django 1.9.7

### ISSUE THREAD

**Issue by fburkitt** [realpython/support#307]
I have tried MANY different approaches to get the migration to work, but I can't figure out how to get around this: 

Traceback (most recent call last):
  File "/Applications/anaconda/envs/dev8/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
  File "/Applications/anaconda/envs/dev8/lib/python3.5/site-packages/psycopg2/**init**.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Applications/anaconda/envs/dev8/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Applications/anaconda/envs/dev8/lib/python3.5/site-packages/psycopg2/_psycopg.cpython-35m-darwin.so
  Reason: image not found

I am sure it is obvious but I am new to postgres

**Comment by mjhea0** [comment]
It looks like you are using Anaconda. If I had to guess it has something to do with the path not being correct in your bash_profile or .bashrc file. I would try without Anaconda since that messes with your environment. Other than that, i don't really know. You could also try using postgres.app.
