### ISSUE TITLE
Python2 + Forums

### ISSUE THREAD

**Issue by ehussong** [realpython/support#309]
I seem to recall this originally being written for Python 2.7, but after downloading it it looks like it's now for Python 3. I actually have a project in Python 2 that I'd like to (finally) learn Python for. Am I mis-remembering or is it possible to get the Python 2.7 version of this course still?

Also, any word on when the new forums might be up?

**Comment by mjhea0** [comment]
There's very, very few syntactical differences between Python 2 and 3. Any time there are differences, we highlighted them in the courses. 

We are in the process of finalizing a new learning management platform, which has a support forum system built it. It should be finished next week, and we will be alpha testing it with a number of Real Python supporters shortly after. Would you be interested in being part of that test? If so, can you email us at info at real python dot com.

Thanks!

Check out the staging version here -> http://textbook-lms.herokuapp.com/
