### ISSUE TITLE
Regarding the mentoring sessions

### ISSUE THREAD

**Issue by adrienkwong** [realpython/support#310]
Hi,

I'd like to know if I purchase a mentoring session today, when will I have the session the soonest?

Also, my time zone is GMT+8. What time are the mentors available?

Thanks.

**Comment by j1z0** [comment]
Hi Adrien,

Thanks for the query.  In terms of timing for the first session, we will have to schedule a time that fits everybody.  Our Mentors are currently on US time zone GMT -5 and GMT -3.  Before we scheduled a fair bit to GMT +8 by doing morning for the GMT +8 and evening the previous day for the us side.

If you would like to send a mail to info at real python dot com, we can discuss further and schedule a time.

Thanks,
Jeremy
