### ISSUE TITLE
Having problem with popular posts and add_post links

### ISSUE THREAD

**Issue by ezechidc** [realpython/support#311]
Hi,

Can you help me am stuck page 561 real python book 2. I did the two home work see code attached, but when I click on the link to Popular Posts it doesn't respond. I then moved on to add_post the same thing is still happening can you look through my code and correct me please.

Regards,

Dennis. 

[Bloggy.zip](https://github.com/realpython/support/files/419125/Bloggy.zip)

**Comment by mjhea0** [comment]
I will respond to your email shortly.
