### ISSUE TITLE
Part 2, p. 338: "Behave" is behaving unexpectedly

### ISSUE THREAD

**Issue by stonemirror** [realpython/support#312]
I'm working through the "Behavior-Driven Development" chapter, and I've run into a problem around p. 338. My tests to find a message in the page returned seem to be failing in a way that isn't reflected when I run the app using "python flaskr.py" and access it in a browser.

After Googling around some, I made a small change to the "we should see the alert..." strp:

```
@then(u'we should see the alert "{message}"')
def message(context, message):
    assert message in context.page.data, "%r not in %r!" % (message, context.page.data)
```

I'm not seeing the index page after login, for example. When I run my Behave testing, I get output like the following:

```
  Scenario: successful login                          # features/auth.feature:3
    Given flaskr is set up                            # features/steps/auth_steps.py:19 0.000s
    When we log in with "admin" and "admin"           # features/steps/auth_steps.py:23 0.126s
    Then we should see the alert "You were logged in" # features/steps/auth_steps.py:38 0.000s
      Assertion Failed: u'You were logged in' not in '<div class="container">
        <h1>Flask - BDD</h1>
        
        <h3>Login</h3>
        
        <form action="/login/" method="post">
          <dl>
            <dt>Username:</dt>
            <dd><input type="text" name="username">
              <dt>Password:</dt>
              <dd><input type="password"  name="password">
              <br>
              <br>
              <dd><input type="submit" class="btn btn-default" value="Login">
              <span>Use "admin" for the username and password</span>
          </dl>
        </form>
      </div>'!
```

**Comment by stonemirror** [comment]
I got it sorted out: my problem turned out to be inconsistencies in the way I was expressing the routes in various places, e.g. "/login" vs. "/login/".

**Comment by mjhea0** [comment]
If you keep having problems with URL inconsistencies then you can always turn strict slashes off ->http://werkzeug.pocoo.org/docs/0.10/routing/#rule-format
