### ISSUE TITLE
Part 2 django_ecommerce project Bug

### ISSUE THREAD

**Issue by Qqlick** [realpython/support#315]
Stripe doesn't support TLS 1.0 connections now. 

How to upgrade to TLS 1.2 or later?  

AuthenticationError at /register
Request req_9DqndZVzs3J3Qv: Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.

**Comment by mjhea0** [comment]
Looking into this now...

**Comment by aoy12** [comment]
I had the same issue guys, I was able to get around this issue by upgrading to python 2.7.12. One stackoverflow answer advised to use 2.7.9+, 

I have yet hit another roadblock though in that I am getting an invalid request error from the API.

**Comment by mjhea0** [comment]
We are going to have this updated soon. Have you followed this directions? https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#python

**Comment by aoy12** [comment]
Yeah, I tried. The only resolution was to upgrade python from 2.7.9 to 2.7.12. Thereafter,  I hit the other roadblock as I mentioned.

**Comment by mjhea0** [comment]
Can I see your code? Is it on github?

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
