### ISSUE TITLE
I paid but didn't get email for download

### ISSUE THREAD

**Issue by medeng** [realpython/support#316]
Can you please email to phamlance@gmail.com
I paid with PayPal here:

October 4, 2016
Real Python
-negative $60.00
Payment
Paid with
WELLS FARGO BANK NA x-6101
Transaction ID
95149565TW1505816
Seller info
Real Python
https://www.realpython.com
Your purchase
Real Python - All Courses$60.00
Shipping$0.00
Tax$0.00
Purchase total$60.00
Fee$0.00
Total$60.00
Need help?
If there's a problem, make sure to contact the seller through PayPal by April 3, 2017.

**Comment by mjhea0** [comment]
Can you please email us an into at realpython dot com. Thanks!
