### ISSUE TITLE
Part2, Chapter10: SQLAlchemy - Register User

### ISSUE THREAD

**Issue by cpuskarz** [realpython/support#318]
I'm having a challenge with this chapter - I can't register a new user.However, I can update/delete/add tasks and even manually create a user via the SQL Browser.

I've built the code twice and debugged. I gave up on that and pulled down your files from your git repo and still have the same problem. I have no warnings/errors, logs have: 127.0.0.1 - - [05/Nov/2016 12:28:24] "POST /register/ HTTP/1.1" 200 . 

MAC OS X 10.11.6
Running SQLlite Version 3.9.1

The user isn't being written to the db. any ideas?
thx

**Comment by cpuskarz** [comment]
Found issue. Username needs to be 6 characters or more. Where is this configured? or is this a default?

**Comment by mjhea0** [comment]
The `wtf` validators: https://github.com/realpython/book2-exercises/blob/master/flasktaskr-02/project/forms.py#L31
