### ISSUE TITLE
Real Python Book 2 Chapter 17

### ISSUE THREAD

**Issue by carlps** [realpython/support#322]
Chapter 17 - specifically section 17.9 is missing some detail. The auth_steps.py code (incorrectly labeled as auth.steps) does not cover all the pieces of the auth.feature. Additionally, the code in the repository does not match the code snippets in the book.

Also, 17.10.8 doesn't tell you which file to update.

Thanks!
Carlos

**Comment by mjhea0** [comment]
Updating...

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
