### ISSUE TITLE
Can you please explain how backref works?

### ISSUE THREAD

**Issue by mntolia** [realpython/support#323]
Hi,
Can you please explain further how backref works in the flasktaskr program:
tasks = db.relationship('Task',backref='poster')

I saw the SQLAlchemy documentation but I did not understand it.

I noticed you used it on the Jinja2 templates.

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
