### ISSUE TITLE
Stripe no longer supports API requests made with TLS 1.0

### ISSUE THREAD

**Issue by jonworkman88** [realpython/support#324]
Hi,

I got right to the end of Real Python 2: django ecommerce app. I finally registered a user with Stripe and I got the following error:

AuthenticationError: Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later.

I upgraded Stripe to the 1.19.1 to start and then the latest version, as per the recommendation on Stripes web site, but the error continued. 

Has anyone else raised this issue? Do you guys have a fix?

Thank you 

Jon

PS. Bought all 3 books and they are certainly AWESOME!

**Comment by mjhea0** [comment]
Hi @jonworkman88,

Yes, we are aware of the issue. In fact, if all goes well with refactoring over the weekend, we should have a new release out on Monday. If not, it will come out some time next week. 

Thanks!!
