### ISSUE TITLE
Download link is broken for direct download and dropbox.

### ISSUE THREAD

**Issue by sicksbyproxy** [realpython/support#326]
The "Python Programming By Example" download link is broken.
![screen shot 2016-12-22 at 11 58 51 am](https://cloud.githubusercontent.com/assets/8833336/21413894/075a2c6a-c83e-11e6-896e-f84e16430591.png)

Can't save to dropbox either. Please send me the download link

**Comment by mjhea0** [comment]
Can you please email us at info at realpython dot com?
