### ISSUE TITLE
Book 1 Page 252 Note

### ISSUE THREAD

**Issue by msciences-dev** [realpython/support#327]
The note at the bottom of the page gave me some trouble.

r'\ds[a-z]*'

I think there is a typo in your expression to grab the word "done".  I found some alternative expressions that worked, but was curious what you were going for with the above.

Thanks!

**Comment by mjhea0** [comment]
My bad. That should be -

`r\ds[a-z]*`

**Comment by mjhea0** [comment]
What did you end up with?
