### ISSUE TITLE
About 9+ hours videos

### ISSUE THREAD

**Issue by koztay** [realpython/support#335]
Dear Sirs,
I have purchased you course and downloaded the course materials. But there was no any video in the package. Although you say in the sales page that there are 9+ hours of videos. Where can I download or watch the mentioned videos? I see that you send the video links by email. So, my email is as follows: koztay@me.com which I used it also for purchase. 
Best Regards,
Kemal

**Comment by mjhea0** [comment]
Just emailed you.
