### ISSUE TITLE
Error with spacing of SQL in Python (real python book 2)

### ISSUE THREAD

**Issue by jjmountain** [realpython/support#336]
On page 57 of the 2nd Real Python book I have copied out your example python script (03_sql.py) space for space exactly as you have presented the example. This throws an error when I run the python script as follows:

"IndentationError: unindent does not match any outer indentation level
(vent) Jamess-MacBook-Air:sql jjmountain$ python 03_sql.py
  File "03_sql.py", line 9
    cities = [
             ^
![screenshot 2017-03-06 19 17 26](https://cloud.githubusercontent.com/assets/21108437/23607880/a446a448-02a1-11e7-8ed1-520ea08e00e1.png)

It seems like you've made a mistake with the spacing in the example script. I've tried playing around with it but can't stop this error from occurring. Please could you help?

**Comment by jjmountain** [comment]
I managed to fix the incorrect spacing using a tool I found online. I ran the script and it worked but then when I opened the database in DBBroser it wasn't updated. I think something may be missing from the script. Please could you check this also?

**Comment by mjhea0** [comment]
Yes, the `executemany` needs to be inside the `with` block:

```
# executemany() method


import sqlite3

with sqlite3.connect("new.db") as connection:
    c = connection.cursor()

    # insert multiple records using a tuple
    # (you can copy and paste the values)
    cities = [
                ('Boston', 'MA', 600000),
                ('Los Angeles', 'CA', 38000000),
                ('Houston', 'TX', 2100000),
                ('Philadelphia', 'PA', 1500000),
                ('San Antonio', 'TX', 1400000),
                ('San Diego', 'CA', 130000),
                ('Dallas', 'TX', 1200000),
                ('San Jose', 'CA', 900000),
                ('Jacksonville', 'FL', 800000),
                ('Indianapolis', 'IN', 800000),
                ('Austin', 'TX', 800000),
                ('Detroit', 'MI', 700000)
            ]

    c.executemany("INSERT INTO population VALUES(?, ?, ?)", cities)

    c.execute("SELECT * FROM population WHERE population > 1000000")

    rows = c.fetchall()

    for r in rows:
        print(r[0], r[1], r[2])
```

I just checked the course and the code is valid. It may be how the copy and paste is working. You may want to try right-clicking and select "paste and match style"

**Comment by jjmountain** [comment]
Thanks for your help. I can't believe I didn't see this. Sometimes what is hardest to see is right in front of you, as they say (등잔 밑이 어둡다)
