### ISSUE TITLE
Problem with Testing chapter book two

### ISSUE THREAD

**Issue by funkenpedro** [realpython/support#337]
Below are the test and the process that it tests. This test fails for me and I don't think it should pass because the logout will return Goodbye regardless of whether the user is logged in.

def test_not_logged_in_users_cannot_logout(self):
        response = self.logout()
        self.assertNotIn(b'Goodbye!', response.data)

@app.route('/logout/')
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    flash('Goodbye!')
    return redirect(url_for('login'))

**Comment by funkenpedro** [comment]
I just noticed, the realpython text indicates that the 17 tests in this exercise get executed in under a second, whereas on my windows machine, these take 10 seconds.

**Comment by mjhea0** [comment]
The login required prevents them from being able to access the view function if they are not logged in.

https://github.com/realpython/book2-exercises/blob/master/flasktaskr-04/project/views.py#L66
