### ISSUE TITLE
"Flask: Quick Start": python app.py | app.config['DEBUG'] , did not work

### ISSUE THREAD

**Issue by R110** [realpython/support#347]
Pg 48 app.config['DEBUG'] did not work, had to go to command line and 'export FLASK_DEBUG=1' 

Pg 40 python app.py did not work, had to instead at command line 'export FLASK_APP=app.py' 

Am I missing something?

**Comment by mjhea0** [comment]
@R110 which version of Flask are you using?

**Comment by R110** [comment]
Flask 0.12.1 / Python 3.6.0 ... not getting an error message or any result with 'python app.py'
