### ISSUE TITLE
Inserting into a table SQLite3

### ISSUE THREAD

**Issue by SRoadknight** [realpython/support#348]
Hi,
I am currently working through the course, I have a quick question about the INSERT INTO statement.

I am just wondering if there is a reason you have used two different ways in the following sets of code? Anything in particular I should know about how they work differently?

Inserting cities into a table using a tuple:
![python1](https://cloud.githubusercontent.com/assets/17357638/25428373/9027d1aa-2a6d-11e7-85ec-c0fe6c7075d9.png)

Inserting employees into a table from a CSV file:
![python2](https://cloud.githubusercontent.com/assets/17357638/25428377/94533fd0-2a6d-11e7-8b25-620444e28595.png)

Regards,
Simon

**Comment by mjhea0** [comment]
The first example shows how to enter hard-coded data (in the list) while the second example details how to insert data from a CSV. If you have a CSV full of data you should always use the second method. Make sense?
