### ISSUE TITLE
InvalidRequestError at /register - No such token: None

### ISSUE THREAD

**Issue by narchiii** [realpython/support#355]
I'm using python anywhere to get the e-commerce site from book 2 online. Everything works locally but when I build it on Python Anywhere then go to register I get this error.

InvalidRequestError at /register
Request req_AdeMmUYTM0OMwl: No such token: None

I am wondering if I need to change my code for python anywhere or for production servers in general?

Here is my view. Sorry to ask such a hard to answer question. However, any insight would be much appreciated.

https://gist.github.com/narchiii/a7bed18133dc5e125c2c2ccc432f1408

**Comment by narchiii** [comment]
In case it helps anyone I figured it out. I had stored my static files in the wrong directory. 

According to the people at stripe the codebase you provide is perfect!

**Comment by mjhea0** [comment]
Thanks! So, nothing that we need to change on our end, correct?

**Comment by narchiii** [comment]
Exactly. Your code and explanation is all good.
