### ISSUE TITLE
Question: OpenCV 3+ and Python 3+ onto Heroku?

### ISSUE THREAD

**Issue by markelIdeas** [realpython/support#358]
Do you offer a course on steps to deploy both OpenCV 3+ and Python 3+ onto Heroku?  Many, many thanks.

Sorry if this isn't the proper forum to ask questions.

Steve Markel

**Comment by alexmitev** [comment]
I`m wondering if there`s a proper forum to post questions

**Comment by dbader** [comment]
Hi @alexmitev, we don't offer a course specifically on OpenCV and Heroku deployments. I'd recommend you check out Adrian Rosebrock's [Py Image Search](https://www.pyimagesearch.com/), he also has a forum specifically for Python computer vision questions.

Happy Pythoning!

— Dan
