### ISSUE TITLE
Unable to install Flash using pip

### ISSUE THREAD

**Issue by chibole** [realpython/support#362]
I am in book 2 of the series, and have just started learning Flash. However, when I run the command to install flash: _pip install flash_
I get an error message: _Could not find version that satisfies the requirement flash (from versions:) No matching distribution found for flash_.
My efforts to google and at stackoverflow has not been successful. Kindly assist. I am using Windows 7 and i typed the command in command prompt.

James Paul Chibole

**Comment by mjhea0** [comment]
@chibole it's `flask`, not `flash`. Try `pip install flask`.

**Comment by chibole** [comment]
Sorry, l actually meant flash. It's the one l typed: pip install flash
I still get the problem.

**Comment by mjhea0** [comment]
You don't have to install `flash`. it is a module that can be imported from Flask:

```
from flask import flash
```

So, as long as you install Flask, you'll be able to import flash.

More info -> http://flask.pocoo.org/docs/0.12/patterns/flashing/

**Comment by chibole** [comment]
thank you, but throughout I was confusing flask with flash. I am new to
flask and I just want to follow what the book says, untill I come across
flash. Otherwise, if I start reading about flash now it might just confuse
me as a new person to flask. Thank you and will bookmark the link for my
future use.

Regards.
