### ISSUE TITLE
"new.db"

### ISSUE THREAD

**Issue by ryentzer** [realpython/support#363]
As I been working through part 2, I noticed that most, if not all of the sql code examples reference the same database:

    with sqlite3.connect("new.db") as connection:

For the most part, I was able to create the databases with names that made sense, but once I got to the _joins_ section of the Multiple Databases chapter it created some confusion.

Do you mean for all the db's to be the same? I ended up creating separate ones like:

+ cars.db
+ population.db
+ ...

**Comment by mjhea0** [comment]
It just takes practice. Check out https://pgexercises.com/.

Separate DBs are fine. You can view the answers here -> https://github.com/realpython/book2-exercises/tree/master/sql
