### ISSUE TITLE
print elaborate in Python Spyder

### ISSUE THREAD

**Issue by sankarachari** [realpython/support#364]
Hi Bloggers...!

Greetings of the day..
Can anyone help me out on the below issue:
"**print (boston.feature_names)
['CRIM' 'ZN' 'INDUS' ..., 'PTRATIO' 'B' 'LSTAT']**"

The print command does not prints the entire array of names. 
How can we get the list of all feature names displayed ?

Thanks in advance.

**Comment by mjhea0** [comment]
@sankarachari sorry this support is only for the Real Python courses.
