### ISSUE TITLE
Error on scraping Opendata.Socrata

### ISSUE THREAD

**Issue by mntolia** [realpython/support#365]
Hi,
In chapter 2 I am getting an error in the Socrata Chapter of Web Scraping.
It says on the terminal:
`twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')]>]
`
I tried http:// and https://.
I reinstalled scrapy and pyopenssl.
I tried with the Scrapy Shell.
I tried with the latest version of Srapy.

But I keep getting this error. I am not able to move forward.

**Comment by mjhea0** [comment]
This is a tricky issue. It's more often than not and issue with openssl. Can you try scraping from a different site that also uses https?

https://github.com/scrapy/scrapy/issues/1429

**Comment by mntolia** [comment]
Yea I scraped from Wikipedia which was the chapter before the opendata one. It worked fine.

**Comment by mjhea0** [comment]
Yes, the wikipedia example uses "http" not "https". Can you try a different site with "https"? I cannot recreate the error on my end.

**Comment by mntolia** [comment]
I used https when I scraped from wikipedia and news.ycombinator. It did not throw any errors.
