### ISSUE TITLE
I purchased real python last year...

### ISSUE THREAD

**Issue by Bonejob** [realpython/support#368]
I purchased Real Python last year and I just downloaded the updated package from simplegoods.co (V2.2.0) it does not seem to include the Python 3 version of the book. I realize it is just syntactical differences, but I would find it useful to be able to use a reference.

**Comment by dbader** [comment]
Hey @Bonejob can you email us at info@realpython.com and mention this conversation? I want to get this sorted out and make sure you've got access to the latest version of the course. Cheers :)
