### ISSUE TITLE
Web scraping code in Real Python Book 1 does not work

### ISSUE THREAD

**Issue by dgremmell19** [realpython/support#375]
When working through the web scraping chapter, which is 14, the following web page returns an error because it does not appear to exist:

"https://realpython.com/practice/aphrodite.html"

Is there a new page that can be used to practice?

**Comment by dbader** [comment]
@dgremmell19 Thanks for the bug report—this is an issue with our new hosting infrastructure. Our CDN (CloudFlare) flags scrapers and bots and blocks them from accessing the site after a few tries. Unfortunately the course material references some pages hosted on realpython.com

We're working on a big update to the Real Python Course right now that should come out in the next few weeks that will revamp these exercises. So please stay tuned and thanks again for the report :)
