### ISSUE TITLE
Incorrect Video for #4 in 'Top 10 Must-Watch PyCon Talks'

### ISSUE THREAD

**Issue by leahein** [realpython/support#377]
In the article [Top 10 Must-Watch PyCon Talks](https://realpython.com/must-watch-pycon-talks), # 4 lists the topic as [Memory Management in Python: The Basics](https://realpython.com/must-watch-pycon-talks/#4-memory-management-in-python-the-basics).  
However, the embedded video is to [Nina Zakharenko - Elegant Solutions For Everyday Python Problems - PyCon 2018](https://www.youtube.com/watch?v=WiQqqB9MlkA&feature=youtu.be), a talk given at pycon in 2018.  The correct video should be [Nina Zakharenko - Memory Management in Python - The Basics - PyCon 2016](https://www.youtube.com/watch?v=F6u5rhUQ6dU)

**Comment by mertzjames** [comment]
nice catch!  I've updated the article.

**Comment by dbader** [comment]
Thanks @leahein @mertzjames :)
