### ISSUE TITLE
Suggestion: Book 2 - Homework on page 73 could use better explanation

### ISSUE THREAD

**Issue by mokhann** [realpython/support#62]
Apologies if this is just me being a newbie, but I found the homework assignment on page 73 of the PDF to be a little difficult.

The section above hadn't actually demonstrated the JOIN command at all, and looking at the homework solution, the INNER JOIN command was necessary to complete it. Perhaps a slightly more thorough section on JOINs, or just a prompt for the reader to do a little more reading, would be useful.

Also, I was a little confused on the requirements of the second half of the assignment. They are as follows:

> "Finally output the car’s make and model on one line, the quantity on another line, and
> then the order_dates on subsequent lines below that."

My understanding of this instruction was to have an output such as the following:

```
Honda Prelude
5
2013-12-12
2013-06-14
2013-09-02
```

However, the solution had code outputting this:

```
Honda Prelude
5
2013-12-12

Honda Prelude
5
2013-06-14

Honda Prelude
5
2013-09-02
```

Which is much simpler.

Maybe a slight rewording to avoid confusion.

Again, apologies if this is just me being daft. Really enjoying the books so far!

**Comment by mjhea0** [comment]
Updated in v 2.0 of the courses. Coming week of 12/19/2016. https://github.com/realpython/about/blob/master/changelog.csv
